### PR TITLE
Set origin in case model is in selection reference when create purchase from purchase requests

### PR DESCRIPTION
**Pull request by raimonesteve**
#160335

### CODE REVIEW

**Review by bernatnan — APPROVED** [review]
I haven't searched the code, but wouldn't it be good to add the 'sale.sale' model to the origin source in order to have the relationship? Maybe we already have it and, therefore, it is not necessary.

**Comment by raimonesteve** [comment]
> I haven't searched the code, but wouldn't it be good to add the 'sale.sale' model to the origin source in order to have the relationship? Maybe we already have it and, therefore, it is not necessary.

- sale_supply_drop_shipment is a core module and can not add "sale.sale" model.
- production_operation not depends "sale" module.
- The current design is not correct because it does not control what options are available to us

Solution:
A- Add "sale" module in extras_depends in production_operation
B- Add "sale.sale" origin in the custom module (customer module)

We implement option A.

**Comment by raimonesteve** [comment]
> A- Add "sale" module in extras_depends in production_operation

9b1e46d07c6961fe562eefa30628dcda7e926a99

**Review by bernatnan — APPROVED** [review]
LGTM

**Pull request merged**
